name: Upload Files

on:
  push:
    branches:
      - main

jobs:
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch 
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Track changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed checklist files
        id: changed-checklist-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            checklist-files/**
      - name: List all changed checklist files
        env:
          ALL_CHANGED_CHECKLIST_FILES: ${{ steps.changed-checklist-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_CHECKLIST_FILES}; do
            echo "$file was changed, so post it"
          done
      - name: Get changed compliance scan files
        id: changed-compliancescan-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            compliance-scans/**
      - name: List all changed compliance scan files
        env:
          ALL_CHANGED_COMPLIANCESCAN_FILES: ${{ steps.changed-compliancescan-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_COMPLIANCESCAN_FILES}; do
            echo "$file was changed, so post it"
          done
      - name: Get changed patch scan files
        id: changed-patchscan-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            patch-scans/**
      - name: List all changed patch scan files
        env:
          ALL_CHANGED_PATCHSCAN_FILES: ${{ steps.changed-patchscan-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_PATCHSCAN_FILES}; do
            echo "$file was changed, so post it"
          done
      - name: Post all Patch Scan Files one at a time
        env:
          ALL_CHANGED_PATCHSCAN_FILES: ${{ steps.changed-patchscan-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_PATCHSCAN_FILES}; do
            curl -X POST -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.OPENRMFPRO_API_TOKEN }}" -F "patchscanFile=@$file" ${{ secrets.OPENRMFPRO_API_ROOT_URL }}/api/external/systempackage/${{ secrets.OPENRMFPRO_API_SYSTEMKEY }}/patchscan/\?applicationKey\=${{ secrets.OPENRMFPRO_API_APPLICATIONKEY }}
          done